# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4a541d4262f413ff8a97e482d784d82b3b6630e4be1b52273d5c6758f7cbf2ef3aa6c873e3ac05e71b4ada532a3ac6bed160971f5f7f43d0a5021069568b118d
  salesforce:
    host: login.salesforce.com
    client_secret: 4818646395696774671
    client_id: 3MVG9Y6d_Btp4xp47m.v0oSeiILQ7__JU8S.OzXar5eTlcc7JIKGjuD1qkzhPaRHRL2.qmTaTvAYhaI4FKZNe
    debugging: true                   # Can be useful while developing
    reset_password_token: gEIgDEqkyqAcNDPcFKryO58B
    username: 'aditya@vinsol.com'
    password: 'Password1!gEIgDEqkyqAcNDPcFKryO58B'

test:
  secret_key_base: 3fd2cfb5c6e61a137253c32510ad8ecd2ba98b6ca75ad02cd06edd60ae7ae8ca1591b2280298df99d5e3d7ec302284a7637815b1373f903fd4b03deb156354a3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
